export const validations = {
  email: "Please enter a valid email address.(ex: your_name@gmail.com)",
  dob: "Please select a valid date of birth",
  phone: "Please enter a valid 10-digit contact number ",
  emergencyContact: "Please enter a valid 10-digit emergency contact number",
  whatsAppContact: "Please enter a valid 10-digit WhatsApp number",
  firstName: "Please enter a valid first name",
  lastName: "Please enter a valid last name",
  gender: "Please select a gender",
  otp: "The OTP entered is incorrect. Please try again.",
  password:
    "Your password should be at least 8 characters long and include a mix of upper and lower case letters, numbers, and special characters.",
  confirmPassword: "The passwords entered do not match. Please try again.",
  usn: "Please enter a valid USN ID",
  percentage: "Please enter a valid percentage (35-100)",
  cgpa: "Please enter a valid CGPA (1-10)",
  sslcSchoolName: "Please select a valid school name",
  yearOfPassout: "Please select a valid year",
  graduationActiveBacklog: "Please enter a valid backlog count (0-30)",
  collegeName: "Please select a valid college name",
  course: "Please select a valid course",
  branch: "Please select a valid branch/stream",
  postGraduationActiveBacklog: "Please select a valid backlog count",
  gapInAcademics: "Please enter a valid gap in years (0-10)",
  workingProfessional: "Please select Yes or No",
  workExperience: "Please select a valid work experience range",
  state: "Please select a valid state",
  city: "Please select a valid city",
  preferredJobLocation: "Please select a valid job location",
  tpoName: "Please enter a valid name",
  tpoEmail: "Please enter a valid email address.",
  url: "Please enter a valid URL",
};
